2023-09-15 17:48:07.819 [Error] {"ExceptionMessage":"An error occurred while saving the entity changes. See the inner exception for details.","MethodName":"AddAsync","User":"?","Parameters":[{"Name":"entity","Value":{"Content":"string","TeamId":1,"UserId":1},"Type":"CommentAddDto"}]}
2023-09-15 17:48:20.570 [Error] {"ExceptionMessage":"An error occurred while saving the entity changes. See the inner exception for details.","MethodName":"AddAsync","User":"?","Parameters":[{"Name":"entity","Value":{"Content":"string","TeamId":1,"UserId":2},"Type":"CommentAddDto"}]}
2023-09-15 17:48:32.145 [Error] {"ExceptionMessage":"An error occurred while saving the entity changes. See the inner exception for details.","MethodName":"AddAsync","User":"?","Parameters":[{"Name":"entity","Value":{"Content":"string","TeamId":2,"UserId":2},"Type":"CommentAddDto"}]}
